// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-page/ActionFirstCommand.tsx": () => import("../components/mockups/dashboard-page/ActionFirstCommand.tsx"),
  "./components/mockups/dashboard-page/DailyGamePlan.tsx": () => import("../components/mockups/dashboard-page/DailyGamePlan.tsx"),
  "./components/mockups/dashboard-page/FinancialCockpit.tsx": () => import("../components/mockups/dashboard-page/FinancialCockpit.tsx"),
  "./components/mockups/dashboard-page/MemberHealthMatrix.tsx": () => import("../components/mockups/dashboard-page/MemberHealthMatrix.tsx"),
  "./components/mockups/billing-page/MemberLifecycle.tsx": () => import("../components/mockups/billing-page/MemberLifecycle.tsx"),
  "./components/mockups/billing-page/ProgressiveDisclosure.tsx": () => import("../components/mockups/billing-page/ProgressiveDisclosure.tsx"),
  "./components/mockups/billing-page/RevenueCommandCenter.tsx": () => import("../components/mockups/billing-page/RevenueCommandCenter.tsx"),
  "./components/mockups/billing-page/SplitPaneWorkspace.tsx": () => import("../components/mockups/billing-page/SplitPaneWorkspace.tsx")
};
