// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ai-insights-page/ActionStream.tsx": () => import("../components/mockups/ai-insights-page/ActionStream.tsx"),
  "./components/mockups/ai-insights-page/InterventionCommand.tsx": () => import("../components/mockups/ai-insights-page/InterventionCommand.tsx"),
  "./components/mockups/ai-insights-page/StrategicOps.tsx": () => import("../components/mockups/ai-insights-page/StrategicOps.tsx"),
  "./components/mockups/ai-operator-page/AutopilotDashboard.tsx": () => import("../components/mockups/ai-operator-page/AutopilotDashboard.tsx"),
  "./components/mockups/ai-operator-page/ImpactCommandCenter.tsx": () => import("../components/mockups/ai-operator-page/ImpactCommandCenter.tsx"),
  "./components/mockups/ai-operator-page/MissionControl.tsx": () => import("../components/mockups/ai-operator-page/MissionControl.tsx"),
  "./components/mockups/ai-operator-page/MorningBriefing.tsx": () => import("../components/mockups/ai-operator-page/MorningBriefing.tsx"),
  "./components/mockups/billing-page/MemberLifecycle.tsx": () => import("../components/mockups/billing-page/MemberLifecycle.tsx"),
  "./components/mockups/billing-page/ProgressiveDisclosure.tsx": () => import("../components/mockups/billing-page/ProgressiveDisclosure.tsx"),
  "./components/mockups/billing-page/RevenueCommandCenter.tsx": () => import("../components/mockups/billing-page/RevenueCommandCenter.tsx"),
  "./components/mockups/billing-page/SplitPaneWorkspace.tsx": () => import("../components/mockups/billing-page/SplitPaneWorkspace.tsx"),
  "./components/mockups/dashboard-page/ActionFirstCommand.tsx": () => import("../components/mockups/dashboard-page/ActionFirstCommand.tsx"),
  "./components/mockups/dashboard-page/DailyGamePlan.tsx": () => import("../components/mockups/dashboard-page/DailyGamePlan.tsx"),
  "./components/mockups/dashboard-page/FinancialCockpit.tsx": () => import("../components/mockups/dashboard-page/FinancialCockpit.tsx"),
  "./components/mockups/dashboard-page/MemberHealthMatrix.tsx": () => import("../components/mockups/dashboard-page/MemberHealthMatrix.tsx")
};
